users/urls.py
# -*- coding: utf-8 -*-
# __author__ = "Anatkh"
# date: 2019/1/15

from django.urls import re_path
from users.views import accounts, verification

app_name = 'users'
urlpatterns = [
    re_path(r'^register/$', accounts.RegisterView.as_view(), name='register'),
    re_path(r'^login/$', accounts.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', accounts.logout, name='logout'),

    re_path(r'^user/(?P<pk>\d+)/center/$', accounts.center, name='center'),
    re_path(r'^user/(?P<pk>\d+)/pwdchange/$', accounts.PassWordChangeView.as_view(), name='pwd_change'),

    # 极验验证
    re_path(r'^pc-geetest/register', accounts.pcgetcaptcha, name='pcgetcaptcha'),
    # 动态校验注册用户名、邮箱是否已经存在
    re_path(r'^verification/(?P<field>username|email)/$', verification.verifaicate)
]
# 在settings DEBUG = False 非开发者模式下， ALLOWED_HOSTS添加指定域名或者IP
handler404=accounts.page_not_found

users/templates/users/change_pwd.html
{% extends 'users_plus.html' %}
{% load static %}
{% block title %}
    <title>修改密码PLUS+</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'bootstrapvalidator-master/dist/css/bootstrapValidator.css' %}">
{% endblock %}

{% block content %}
    <form action="" id="form-val" novalidate>
        {% csrf_token %}
        <span class="login100-form-title p-b-49">修改密码</span>
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}" class="form_text_label">{{ field.label }}</label>
                {{ field }}
                <span class="ececk_warning error"></span>

                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                <input type="button" class="login100-form-btn " value="保 存">
            </div>
        </div>
    </form>
{% endblock %}

{% block js %}
    <script src="{% static 'bootstrapvalidator-master/dist/js/bootstrapValidator.js' %}"></script>
    <script>
        $(function () {
            $('#form-val').bootstrapValidator({
                excluded: [':disabled', ':hidden', 'csrfmiddlewaretoken'],
                {#                submitButtons: '.login100-form-btn',#}
                feedbackIcons: {//根据验证结果显示的各种图标
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    password1: {
                        validators: {
                            notEmpty: {message: '请输入旧密码'}
                        }
                    },
                    password2: {
                        validators: {
                            notEmpty: {message: '密码不能为空'},
                            different: {  //比较
                                field: 'password1', //需要进行比较的input name值
                                message: '密码不能相同'
                            },
                            callback: {
                                callback: function (value, validator) {
                                    // Check the password strength
                                    if (value.length < 6) {
                                        return {
                                            valid: false,
                                            message: '密码必须超过6个字符'
                                        }
                                    }

                                    if (value === value.toLowerCase()) {
                                        return {
                                            valid: false,
                                            message: '密码必须至少包含一个大写字符'
                                        }
                                    }
                                    if (value === value.toUpperCase()) {
                                        return {
                                            valid: false,
                                            message: '密码必须至少包含一个小写字符'
                                        }
                                    }
                                    if (value.search(/[0-9]/) < 0) {
                                        return {
                                            valid: false,
                                            message: '密码必须至少包含一位数字'
                                        }
                                    }
                                    if (value.length > 15) {
                                        return {
                                            valid: false,
                                            message: '密码不能超过15个字符'
                                        }
                                    }

                                    return true;
                                }
                            }
                        }
                    },
                    confirm_password: {
                        validators: {
                            notEmpty: {message: '请确认密码'},
                            identical: {  //比较是否相同
                                field: 'password2',  //需要进行比较的input name值
                                message: '两次密码不一致'
                            }
                        }
                    }
                }
            });
            $(".login100-form-btn").click(function () {//非submit按钮点击后进行验证，如果是submit则无需此句直接验证
                $("#form-val").bootstrapValidator('validate');//提交验证
                if ($("#form-val").data('bootstrapValidator').isValid()) {//获取验证结果，如果成功，执行下面代码
                    $.ajax({
                        url: "",
                        type: "post",
                        data: $("#form-val").serialize(),
                        success: function (data) {
                            if (data.user) {
                                location.href = "/accounts/login/"
                            } else {
                                $(".error").html("");
                                $(".error").parent().removeClass("has-error");
                                $(".error:first").html(data.msg);
                                $(".error:first").parent().addClass("has-error");
                            }

                        }
                    })
                }
            });

        })

    </script>
{% endblock %}

users/templates/users/login.html
{% extends 'users_plus.html' %}
{% load static %}

{% block title %}
    <title>登陆PLUS+</title>
{% endblock %}
{% block css %}
    <style>
        /* 极验验证的样式 */
        #embed-captcha {
            width: 300px;
            margin: 0 auto;

        }

        .show {
            display: block;
        }

        .hide {
            display: none;
        }

        #notice {
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="" novalidate>
        {% csrf_token %}
        <span class="login100-form-title p-b-49">登录</span>
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}" class="form_text_label">{{ field.label }}</label>
                {{ field }}
                <span class="ececk_warning error"></span>

                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        {# 验证码开始 #}
        <div class="form-group">
            <div id="embed-captcha" style="width: 390px"></div>
            <p id="wait" class="show">正在加载验证码......</p>
            <p id="notice" class="hide">请先拖动验证码到相应位置</p>
            <span class="ececk_warning error" id="id_verification"></span>
        </div>
        {# 验证码结束 #}

        <div class="text-right p-t-8 p-b-31">
            <a href="javascript:">忘记密码？</a>
        </div>

        <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                <input type="button" class="login100-form-btn " value="登 陆">
            </div>
        </div>
    </form>
{% endblock %}


{% block login_register %}
    <div class="flex-col-c p-t-25">
        <a href="{% url 'users:register' %}" class="txt2">立即注册</a>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'users_plus/js/gt.js' %}"></script>
    <script>
        var handlerEmbed = function (captchaObj) {
            //验证码展开开始
            $("#embed-submit").click(function (e) {

                var validate = captchaObj.getValidate();
                if (!validate) {
                    $("#notice")[0].className = "show";
                    setTimeout(function () {
                        $("#notice")[0].className = "hide";
                    }, 1000);
                    e.preventDefault();
                }
            });
            // 将验证码加到id为captcha的元素里，同时会有三个input的值：geetest_challenge, geetest_validate, geetest_seccode
            captchaObj.appendTo("#embed-captcha");
            captchaObj.onReady(function () {
                $("#wait")[0].className = "hide";
            });
            //验证码展开结束


            $(".login100-form-btn").click(function () {
                //captchaObj.getValidate()获取校验，用于判断是否进行了校验
                if (captchaObj.getValidate()) {//已进行了滑动验证
                    var validate = captchaObj.getValidate();
                    $.ajax({
                        url: "",
                        type: "post",
                        data: {
                            csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),//一定要放在第一个，否则会发生恶心的bug
                            username: $("[name='username']").val(),
                            password: $("[name='password']").val(),
                            geetest_challenge: validate.geetest_challenge,
                            geetest_validate: validate.geetest_validate,
                            geetest_seccode: validate.geetest_seccode
                        },
                        success: function (data) {
                            if (data.user) {
                                location.href = "/index/"//自行设置跳转URL
                            }
                            else {//失败
                                //$(".error").html("");//每次点击后清空错误
                                //$(".error").parent().removeClass("has-error");//每次点击后清空has-error(bootstrap自带属性，让边框变红)这个class
                                //展现此次提交的错误信息，遍历data.msg,function(key,value){}
                                $.each(data.msg, function (field, error_list) {

                                    $("#id_" + field).next().html(error_list[0]);//找到id_key(user/pwd/re_pwd...)的下一个标签.next()
                                    $("#id_" + field).parent().addClass("has-error");//拿到父标签，添加addclass("has-error")，输入框错误变红

                                    //一秒后清空提醒
                                    {#                            setTimeout(function () {//定时器#}
                                    {#                                $(".error").text("")//由data.msg变成空字符串#}
                                    {#                            }, 1000)#}
                                })
                            }
                        }
                    })

                } else {//未进行滑动验证，需要进行滑动验证

                    $.ajax({
                        url: "",
                        type: "post",
                        data: {
                            csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),//一定要放在第一个，否则会发生恶心的bug
                            username: $("[name='username']").val(),
                            password: $("[name='password']").val()
                        },
                        success: function (data) {
                            if (data.user) {
                                location.href = "/index/"//自行设置跳转URL
                            }
                            else {//失败
                                if (data.msg.verification) {
                                    $("#id_verification").html(data.msg.verification[0]);
                                }
                                $.each(data.msg, function (field, error_list) {
                                    $("#id_" + field).next().html(error_list[0]);//找到id_key(user/pwd/re_pwd...)的下一个标签.next()
                                    $("#id_" + field).parent().addClass("has-error");//拿到父标签，添加addclass("has-error")，输入框错误变红

                                    //一秒后清空提醒
                                    {#                                setTimeout(function () {//定时器#}
                                    {#                                    $(".error").text("")//由data.msg变成空字符串#}
                                    {#                                }, 1000)#}
                                })
                            }
                        }
                    })
                }


            });

            // 当input框获取焦点时将之前的错误清空
            $("#id_username").focus(function () {
                // 将之前的错误清空
                $(".error").html("");//每次点击后清空错误
                $(".error").parent().removeClass("has-error");
            });
            $("#id_password").focus(function () {
                // 将之前的错误清空
                $(".error").html("");//每次点击后清空错误
                $(".error").parent().removeClass("has-error");
            });

        };
        //滑动验证码进行校验
        $.ajax({
            // 获取id，challenge，success（是否启用failback）
            url: "/users/pc-geetest/register?t=" + (new Date()).getTime(), // 加随机数防止缓存
            type: "get",
            dataType: "json",
            success: function (data) {
                // 使用initGeetest接口
                // 参数1：配置参数
                // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
                initGeetest({
                    width: '100%',
                    gt: data.gt,
                    challenge: data.challenge,
                    product: "embed", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                    offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                    // 更多配置参数请参见：http://www.geetest.com/install/sections/idx-client-sdk.html#config
                }, handlerEmbed);
            }
        });
    </script>

{% endblock %}

users/templates/users/personal_center.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人中心</title>
    <link rel="stylesheet" href="{% static 'users_plus/vendor/bootstrap/css/bootstrap.css' %}">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-7">
            <form action="" method="post">
            {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.auto_id }}" class="form_text_label">{{ field.label }}</label>
                        {{ field }}
                        <span class="ececk_warning error"></span>

                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="修改">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
</body>
</html>

users/templates/users/register.html
{% extends 'users_plus.html' %}
{% load static %}
{% block title %}
<title>注册PLUS+</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'bootstrapvalidator-master/dist/css/bootstrapValidator.css' %}">
{% endblock %}

{% block content %}
    <form action="" id="form-val" novalidate>
        {% csrf_token %}
        <span class="login100-form-title p-b-49">注册</span>
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}" class="form_text_label">{{ field.label }}</label>
                {{ field }}
                <span class="ececk_warning error"></span>

                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                <input type="button" class="login100-form-btn " value="注 册">
            </div>
        </div>
    </form>
{% endblock %}

{% block login_register %}
    <div class="flex-col-c p-t-25">
        <a href="{% url 'users:login' %}" class="txt2">已有账号？立即登陆</a>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'bootstrapvalidator-master/dist/js/bootstrapValidator.js' %}"></script>
    <script>
        $(function () {
            $('#form-val').bootstrapValidator({
                excluded: [':disabled', ':hidden', 'csrfmiddlewaretoken'],
                {#                submitButtons: '.login100-form-btn',#}
                feedbackIcons: {//根据验证结果显示的各种图标
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    username: {
                        validators: {
                            notEmpty: {
                                message: '用户名不能为空'
                            },
                            stringLength: {
                                max: 18,
                                min: 6,
                                message: '用户名长度必须在6到18位之间'
                            },
                            callback: {
                                callback: function (value, validator) {
                                    if (value.length < 6) {
                                        return {
                                            valid: false,
                                            message: '用户名必须超过6个字符'
                                        }
                                    }
                                    if (value.lenght >18) {
                                        return {
                                            valid: false,
                                            message:'用户名必须小于18个字符'
                                        }
                                    }

                                    return true;
                                }
                            },
                            regexp: {
                                regexp: /^[a-zA-Z0-9_]+$/,
                                message: '用户名只能包含大写、小写、数字和下划线'
                            },
                            threshold: 5,//有2字符以上才发送ajax请求
                            remote: {
                                url: '/users/verification/username/',
                                message: '用户已存在',
                                delay: 1000,
                                type: 'POST'
                            }
                        }
                    },
                    email: {
                        validators: {
                            notEmpty: {
                                message: '邮箱不能为空'
                            },
                            regexp: {
                                regexp: /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/,
                                message: '邮箱地址格式有误'
                            },
                            threshold: 8,//有2字符以上才发送ajax请求
                            remote: {
                                url: '/users/verification/email/',
                                message: '邮箱已存在',
                                delay: 1000,
                                type: 'POST'
                            }
                        }
                    },
                    password1: {
                        validators: {
                            notEmpty: {message: '密码不能为空'},
                            different: {  //比较
                                field: 'username', //需要进行比较的input name值
                                message: '密码不能与用户名相同'
                            },
                            callback: {
                                callback: function (value, validator) {
                                    // Check the password strength
                                    if (value.length < 6) {
                                        return {
                                            valid: false,
                                            message: '密码必须超过6个字符'
                                        }
                                    }

                                    if (value === value.toLowerCase()) {
                                        return {
                                            valid: false,
                                            message: '密码必须至少包含一个大写字符'
                                        }
                                    }
                                    if (value === value.toUpperCase()) {
                                        return {
                                            valid: false,
                                            message: '密码必须至少包含一个小写字符'
                                        }
                                    }
                                    if (value.search(/[0-9]/) < 0) {
                                        return {
                                            valid: false,
                                            message: '密码必须至少包含一位数字'
                                        }
                                    }

                                    return true;
                                }
                            }
                        }
                    },
                    password2: {
                        validators: {
                            notEmpty: {message: '请再次输入密码'},
                            identical: {  //比较是否相同
                                field: 'password1',  //需要进行比较的input name值
                                message: '两次密码不一致'
                            }
                        }
                    }

                }
            });
            $(".login100-form-btn").click(function () {//非submit按钮点击后进行验证，如果是submit则无需此句直接验证
                $("#form-val").bootstrapValidator('validate');//提交验证
                if ($("#form-val").data('bootstrapValidator').isValid()) {//获取验证结果，如果成功，执行下面代码
                    $.ajax({
                        url: "",
                        type: "post",
                        data: $("#form-val").serialize(),
                        success: function (data) {
                            if (data.user) {
                                location.href = "/users/login/"
                            }
                            else {//失败
                                $(".error").html("");
                                $(".error").parent().removeClass("has-error");
                                $.each(data.msg, function (field, error_list) {
                                    console.log(field, error_list);

                                    $("#id_" + field).next().next().html(error_list[0]);
                                    $("#id_" + field).parent().addClass("has-error");

                                    //一秒后清空提醒
                                setTimeout(function () {//定时器
                                    $(".error").text("")//由data.msg变成空字符串
                                }, 1000)
                                })
                            }
                        }
                    })
                }
            });

        })

    </script>
{% endblock %}